"""
Unified Pipeline Code Generator 
Combines operations from Fix Data, Skewness, and Feature Engineering tabs
Includes sklearn Pipeline export, fitted object serialization, ML templates
"""
import streamlit as st
import pickle
import base64


def generate_complete_pipeline_code():
    """
    Generate Python code for the entire data preparation pipeline.
    Combines cleaning, skewness correction, and feature engineering.
    
    Returns:
        str: Complete Python code as a string
    """
    
    code_lines = [
        "# ============================================================",
        "# COMPLETE DATA PREPARATION PIPELINE",
        "# Auto-generated by Smart CSV AI Studio",
        "# ============================================================",
        "#",
        "# This script combines all transformations applied in:",
        "# 1. Fix Data tab (cleaning & outlier treatment)",
        "# 2. Skewness tab (distribution normalization)",
        "# 3. Feature Engineering tab (scaling & encoding)",
        "#",
        "# Compatible with scikit-learn and ready for production",
        "# ============================================================",
        "",
        "import pandas as pd",
        "import numpy as np",
        "from sklearn.preprocessing import (",
        "    StandardScaler, MinMaxScaler, RobustScaler,",
        "    LabelEncoder, PowerTransformer, QuantileTransformer,",
        "    Normalizer, PolynomialFeatures",
        ")",
        "from sklearn.pipeline import Pipeline",
        "from sklearn.compose import ColumnTransformer",
        "from sklearn.experimental import enable_iterative_imputer",
        "from sklearn.impute import IterativeImputer",
        "from scipy import stats",
        "import joblib  # For saving fitted transformers",
        "",
        "# ============================================================",
        "# LOAD DATA",
        "# ============================================================",
        "df = pd.read_csv('your_data.csv')",
        "print(f'Original shape: {df.shape}')",
        "print(f'Missing values: {df.isna().sum().sum()}')",
        "",
    ]
    
    # ============================================================
    # STEP 1: DATA CLEANING
    # ============================================================
    if 'cleaning_ops' in st.session_state and st.session_state.cleaning_ops:
        ops = st.session_state.cleaning_ops
        
        code_lines.extend([
            "# ============================================================",
            "# STEP 1: DATA CLEANING",
            "# ============================================================",
            "print('\\nSTEP 1: Data Cleaning')",
            "print('=' * 60)",
            ""
        ])
        
        # Handle different cleaning methods
        method = ops.get('method', 'manual')
        
        if method == 'mice':
            code_lines.extend([
                "# MICE Imputation (Multivariate Imputation by Chained Equations)",
                "print('Applying MICE imputation...')",
                ""
            ])
            
            if ops.get('impute_mice'):
                code_lines.extend([
                    "# Impute numeric columns with MICE",
                    f"mice_columns = {ops['impute_mice']}",
                    "",
                    "imputer = IterativeImputer(random_state=42, max_iter=10)",
                    "for col in mice_columns:",
                    "    if col in df.columns and df[col].isna().any():",
                    "        # Prepare data for imputation",
                    "        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()",
                    "        if col in numeric_cols:",
                    "            df[[col]] = imputer.fit_transform(df[[col]])",
                    "            print(f'  ✓ Imputed {col}')",
                    "",
                    "# Save fitted imputer for future use",
                    "joblib.dump(imputer, 'mice_imputer.pkl')",
                    "print('  💾 Saved imputer to mice_imputer.pkl')",
                    ""
                ])
        
        elif method == 'drop':
            code_lines.extend([
                "# Drop rows with missing values",
                "print('Removing rows with missing values...')",
                "original_rows = len(df)",
                "df = df.dropna()",
                "removed = original_rows - len(df)",
                "print(f'  ✓ Removed {removed} rows ({removed/original_rows*100:.1f}%)')",
                ""
            ])
        
        else:  # Manual or mean/mode
            if ops.get('impute_mean'):
                code_lines.extend([
                    "# Fill numeric columns with mean",
                    f"mean_columns = {ops['impute_mean']}",
                    "for col in mean_columns:",
                    "    if col in df.columns:",
                    "        mean_value = df[col].mean()",
                    "        df[col] = df[col].fillna(mean_value)",
                    "        print(f'  ✓ Filled {{col}} with mean ({mean_value:.2f})')",
                    ""
                ])
            
            if ops.get('impute_mode'):
                code_lines.extend([
                    "# Fill categorical columns with mode",
                    f"mode_columns = {ops['impute_mode']}",
                    "for col in mode_columns:",
                    "    if col in df.columns and not df[col].mode().empty:",
                    "        mode_value = df[col].mode()[0]",
                    "        df[col] = df[col].fillna(mode_value)",
                    "        print(f'  ✓ Filled {{col}} with mode ({mode_value})')",
                    ""
                ])
            
            if ops.get('drop_cols'):
                code_lines.extend([
                    "# Drop columns with high missing percentage",
                    f"columns_to_drop = {ops['drop_cols']}",
                    "df = df.drop(columns=[c for c in columns_to_drop if c in df.columns])",
                    "print(f'  ✓ Dropped {len(columns_to_drop)} columns')",
                    ""
                ])
            
            if ops.get('drop_duplicates'):
                code_lines.extend([
                    "# Remove duplicate rows",
                    "original_rows = len(df)",
                    "df = df.drop_duplicates()",
                    "removed = original_rows - len(df)",
                    "print(f'  ✓ Removed {removed} duplicate rows')",
                    ""
                ])
        
        # Outlier treatment
        outlier_treatment = ops.get('outlier_treatment')
        outlier_cols = ops.get('outlier_cols', [])
        
        if outlier_treatment == 'remove':
            code_lines.extend([
                "# Remove outliers using IQR method",
                "print('Removing outliers...')",
                "outlier_sensitivity = 1.5  # Adjust for more/less aggressive removal",
                "original_rows = len(df)",
                "",
                "for col in df.select_dtypes(include=[np.number]).columns:",
                "    Q1 = df[col].quantile(0.25)",
                "    Q3 = df[col].quantile(0.75)",
                "    IQR = Q3 - Q1",
                "    lower_bound = Q1 - outlier_sensitivity * IQR",
                "    upper_bound = Q3 + outlier_sensitivity * IQR",
                "    ",
                "    # Count outliers before removal",
                "    outliers = len(df[(df[col] < lower_bound) | (df[col] > upper_bound)])",
                "    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]",
                "    ",
                "    if outliers > 0:",
                "        print(f'  ✓ Removed {outliers} outliers from {col}')",
                "",
                "removed_total = original_rows - len(df)",
                "print(f'  ✓ Total rows removed: {removed_total} ({removed_total/original_rows*100:.1f}%)')",
                ""
            ])
        
        elif outlier_treatment == 'cap' and outlier_cols:
            code_lines.extend([
                "# Cap outliers (Winsorization)",
                "print('Capping outliers...')",
                f"cap_columns = {outlier_cols}",
                "outlier_sensitivity = 1.5",
                "",
                "for col in cap_columns:",
                "    if col in df.columns:",
                "        Q1 = df[col].quantile(0.25)",
                "        Q3 = df[col].quantile(0.75)",
                "        IQR = Q3 - Q1",
                "        lower_bound = Q1 - outlier_sensitivity * IQR",
                "        upper_bound = Q3 + outlier_sensitivity * IQR",
                "        ",
                "        # Count and cap outliers",
                "        n_outliers = len(df[(df[col] < lower_bound) | (df[col] > upper_bound)])",
                "        df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)",
                "        ",
                "        if n_outliers > 0:",
                "            print(f'  ✓ Capped {n_outliers} outliers in {col}')",
                ""
            ])
        
        elif outlier_treatment == 'log' and outlier_cols:
            code_lines.extend([
                "# Log transform to reduce impact of outliers",
                "print('Applying log transform to reduce outliers...')",
                f"log_columns = {outlier_cols}",
                "",
                "for col in log_columns:",
                "    if col in df.columns and (df[col] > 0).all():",
                "        original_max = df[col].max()",
                "        df[col] = np.log1p(df[col])",
                "        new_max = df[col].max()",
                "        print(f'  ✓ Log transformed {col} (max: {original_max:.2f} → {new_max:.2f})')",
                "    elif col in df.columns:",
                "        print(f'  ⚠️  Skipped {col} (contains non-positive values)')",
                ""
            ])
        
        code_lines.extend([
            "print(f'\\nStep 1 Complete!')",
            "print(f'  Final shape: {df.shape}')",
            "print(f'  Missing values: {df.isna().sum().sum()}')",
            ""
        ])
    
    # ============================================================
    # STEP 2: SKEWNESS CORRECTION
    # ============================================================
    if 'transformations_log' in st.session_state and len(st.session_state.transformations_log) > 0:
        transforms = st.session_state.transformations_log
        
        code_lines.extend([
            "# ============================================================",
            "# STEP 2: SKEWNESS CORRECTION",
            "# ============================================================",
            "print('\\nSTEP 2: Skewness Correction')",
            "print('=' * 60)",
            ""
        ])
        
        for idx, t in enumerate(transforms, 1):
            col = t['column']
            method = t['method']
            shift = t.get('shift', 0)
            
            code_lines.append(f"# Transform {idx}: {col} using {method}")
            code_lines.append(f"# Original skew: {t['original_skew']:.3f} → Target: < |1.0|")
            
            if "Log" in method:
                if shift > 0:
                    code_lines.extend([
                        f"# Shift by {shift:.4f} to handle negative/zero values",
                        f"df['{col}'] = np.log1p(df['{col}'] + {shift:.4f})"
                    ])
                else:
                    code_lines.append(f"df['{col}'] = np.log1p(df['{col}'])")
            
            elif "Square Root" in method:
                if shift > 0:
                    code_lines.extend([
                        f"# Shift by {shift:.4f} to handle negative values",
                        f"df['{col}'] = np.sqrt(df['{col}'] + {shift:.4f})"
                    ])
                else:
                    code_lines.append(f"df['{col}'] = np.sqrt(df['{col}'])")
            
            elif "Cube Root" in method:
                code_lines.append(f"df['{col}'] = np.cbrt(df['{col}'])")
            
            elif "Box-Cox" in method:
                if shift > 0:
                    code_lines.extend([
                        f"# Shift by {shift:.4f} for Box-Cox (requires positive values)",
                        f"df['{col}'], lambda_param = stats.boxcox(df['{col}'] + {shift:.4f})",
                        f"print(f'  Box-Cox lambda for {col}: {{lambda_param:.4f}}')"
                    ])
                else:
                    code_lines.extend([
                        f"df['{col}'], lambda_param = stats.boxcox(df['{col}'])",
                        f"print(f'  Box-Cox lambda for {col}: {{lambda_param:.4f}}')"
                    ])
            
            elif "Yeo-Johnson" in method:
                code_lines.extend([
                    f"df['{col}'], lambda_param = stats.yeojohnson(df['{col}'])",
                    f"print(f'  Yeo-Johnson lambda for {col}: {{lambda_param:.4f}}')"
                ])
            
            elif "Reciprocal" in method:
                code_lines.extend([
                    f"# Avoid division by zero",
                    f"df['{col}'] = 1 / (df['{col}'] + 1e-10)"
                ])
            
            code_lines.extend([
                f"new_skew = df['{col}'].skew()",
                f"print(f'  ✓ {col}: skew {t['original_skew']:.3f} → {{new_skew:.3f}}')",
                ""
            ])
        
        code_lines.extend([
            "print(f'\\nStep 2 Complete!')",
            "print(f'  All {len(transforms)} skewness corrections applied')",
            ""
        ])
    
    # ============================================================
    # STEP 3: FEATURE ENGINEERING
    # ============================================================
    if 'engineering_operations' in st.session_state:
        eng_ops = st.session_state.engineering_operations
        
        has_operations = (
            eng_ops.get('scaling') or 
            eng_ops.get('encoding') or 
            len(eng_ops.get('additional', [])) > 0
        )
        
        if has_operations:
            code_lines.extend([
                "# ============================================================",
                "# STEP 3: FEATURE ENGINEERING",
                "# ============================================================",
                "print('\\nSTEP 3: Feature Engineering')",
                "print('=' * 60)",
                "",
                "# Store fitted transformers for production use",
                "fitted_transformers = {}",
                ""
            ])
            
            # Scaling
            if eng_ops.get('scaling'):
                scaling = eng_ops['scaling']
                method = scaling['method']
                cols = scaling['columns']
                
                code_lines.append("# Feature Scaling")
                code_lines.append(f"# Method: {method}")
                
                if "Standard" in method:
                    scaler_code = "StandardScaler()"
                    scaler_desc = "# Centers data: mean=0, std=1"
                elif "MinMax" in method:
                    scaler_code = "MinMaxScaler()"
                    scaler_desc = "# Scales to [0, 1] range"
                else:
                    scaler_code = "RobustScaler()"
                    scaler_desc = "# Uses median and IQR (robust to outliers)"
                
                code_lines.extend([
                    scaler_desc,
                    f"scaler = {scaler_code}",
                    f"scale_columns = {cols}",
                    "",
                    "# Fit and transform",
                    "df[scale_columns] = scaler.fit_transform(df[scale_columns])",
                    "",
                    "# Save fitted scaler for production",
                    "fitted_transformers['scaler'] = scaler",
                    "joblib.dump(scaler, 'scaler.pkl')",
                    "print(f'  ✓ Scaled {len(scale_columns)} columns')",
                    "print(f'  💾 Saved scaler to scaler.pkl')",
                    ""
                ])
            
            # Encoding
            if eng_ops.get('encoding'):
                encoding = eng_ops['encoding']
                method = encoding['method']
                cols = encoding['columns']
                
                code_lines.append("# Categorical Encoding")
                code_lines.append(f"# Method: {method}")
                
                if "One-Hot" in method:
                    code_lines.extend([
                        "# Creates binary dummy variables for each category",
                        f"encode_columns = {cols}",
                        "",
                        "# Store original columns for tracking",
                        "original_cols = df.columns.tolist()",
                        "",
                        "# Apply one-hot encoding",
                        "df = pd.get_dummies(df, columns=encode_columns, drop_first=False)",
                        "",
                        "# Calculate new columns created",
                        "new_cols = set(df.columns) - set(original_cols)",
                        "print(f'  ✓ One-hot encoded {len(encode_columns)} columns')",
                        "print(f'  ✓ Created {len(new_cols)} new binary features')",
                        ""
                    ])
                else:
                    code_lines.extend([
                        "# Converts categories to integer labels",
                        f"encode_columns = {cols}",
                        "",
                        "# Fit and save label encoders",
                        "label_encoders = {}",
                        "for col in encode_columns:",
                        "    le = LabelEncoder()",
                        "    df[col] = le.fit_transform(df[col].astype(str))",
                        "    label_encoders[col] = le",
                        "    print(f'  ✓ Label encoded {{col}} ({{len(le.classes_)}} categories)')",
                        "",
                        "# Save encoders for production",
                        "fitted_transformers['label_encoders'] = label_encoders",
                        "joblib.dump(label_encoders, 'label_encoders.pkl')",
                        "print(f'  💾 Saved label encoders to label_encoders.pkl')",
                        ""
                    ])
            
            # Additional transforms
            for transform in eng_ops.get('additional', []):
                if transform['type'] == 'normalization':
                    code_lines.extend([
                        f"# {transform['norm']} Normalization",
                        "# Scales each sample (row) to unit norm",
                        f"normalizer = Normalizer(norm='{transform['norm'].lower()}')",
                        f"norm_columns = {transform['columns']}",
                        "df[norm_columns] = normalizer.fit_transform(df[norm_columns])",
                        "print(f'  ✓ Applied {transform['norm']} normalization to {len(norm_columns)} columns')",
                        ""
                    ])
                
                elif transform['type'] == 'power':
                    method = 'yeo-johnson' if 'Yeo' in transform['method'] else 'box-cox'
                    code_lines.extend([
                        f"# {transform['method']} Power Transform",
                        f"pt = PowerTransformer(method='{method}')",
                        f"power_columns = {transform['columns']}",
                        ""
                    ])
                    
                    if method == 'box-cox':
                        code_lines.extend([
                            "# Validate Box-Cox requirements (strictly positive)",
                            "for col in power_columns:",
                            "    if (df[col] <= 0).any():",
                            "        print(f'  ⚠️  Warning: {{col}} contains non-positive values')",
                            "        power_columns.remove(col)",
                            ""
                        ])
                    
                    code_lines.extend([
                        "if power_columns:",
                        "    df[power_columns] = pt.fit_transform(df[power_columns])",
                        "    fitted_transformers['power_transformer'] = pt",
                        "    joblib.dump(pt, 'power_transformer.pkl')",
                        "    print(f'  ✓ Power transformed {len(power_columns)} columns')",
                        "    print(f'  💾 Saved power transformer to power_transformer.pkl')",
                        ""
                    ])
                
                elif transform['type'] == 'quantile':
                    code_lines.extend([
                        f"# Quantile Transform (Output: {transform['output_distribution']})",
                        "# Maps features to uniform or Gaussian distribution",
                        f"qt = QuantileTransformer(output_distribution='{transform['output_distribution']}')",
                        f"quantile_columns = {transform['columns']}",
                        "df[quantile_columns] = qt.fit_transform(df[quantile_columns])",
                        "fitted_transformers['quantile_transformer'] = qt",
                        "joblib.dump(qt, 'quantile_transformer.pkl')",
                        "print(f'  ✓ Quantile transformed {len(quantile_columns)} columns')",
                        "print(f'  💾 Saved quantile transformer to quantile_transformer.pkl')",
                        ""
                    ])
                
                elif transform['type'] == 'polynomial':
                    code_lines.extend([
                        f"# Polynomial Features (Degree: {transform['degree']})",
                        "# Creates interaction terms and polynomial features",
                        f"poly = PolynomialFeatures(degree={transform['degree']}, include_bias=False)",
                        f"poly_columns = {transform['columns']}",
                        "",
                        "# Generate polynomial features",
                        "poly_features = poly.fit_transform(df[poly_columns])",
                        "poly_feature_names = poly.get_feature_names_out(poly_columns)",
                        "",
                        "# Replace original columns with polynomial features",
                        "df = df.drop(columns=poly_columns)",
                        "poly_df = pd.DataFrame(poly_features, columns=poly_feature_names, index=df.index)",
                        "df = pd.concat([df, poly_df], axis=1)",
                        "",
                        "# Save polynomial transformer",
                        "fitted_transformers['polynomial'] = poly",
                        "joblib.dump(poly, 'polynomial_features.pkl')",
                        "print(f'  ✓ Created {len(poly_feature_names)} polynomial features')",
                        "print(f'  💾 Saved polynomial transformer to polynomial_features.pkl')",
                        ""
                    ])
            
            code_lines.extend([
                "print(f'\\nStep 3 Complete!')",
                "print(f'  Final shape: {df.shape}')",
                ""
            ])
    
    # ============================================================
    # SAVE FINAL DATASET & FITTED TRANSFORMERS
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# SAVE FINAL DATASET & PIPELINE",
        "# ============================================================",
        "output_filename = 'data_ml_ready.csv'",
        "df.to_csv(output_filename, index=False)",
        "",
        "# Save all fitted transformers as a single pipeline",
        "if fitted_transformers:",
        "    joblib.dump(fitted_transformers, 'complete_pipeline.pkl')",
        "    print('\\n💾 Saved all fitted transformers to complete_pipeline.pkl')",
        "",
        "print('\\n' + '='*60)",
        "print('✅ PIPELINE COMPLETE!')",
        "print('='*60)",
        "print(f'📊 Final shape: {df.shape}')",
        "print(f'📁 Columns: {len(df.columns)}')",
        "print(f'❌ Missing values: {df.isna().sum().sum()}')",
        "print(f'💾 Saved to: {output_filename}')",
        "print('='*60)",
        "",
    ])
    
    # ============================================================
    # ✨ NEW: SKLEARN PIPELINE FOR PRODUCTION
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# SKLEARN PIPELINE FOR PRODUCTION (RECOMMENDED)",
        "# ============================================================",
        "# from sklearn.pipeline import Pipeline",
        "# from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier",
        "# from sklearn.linear_model import LogisticRegression",
        "# from sklearn.svm import SVC",
        "# ",
        "# # Example: Create end-to-end ML pipeline",
        "# # This ensures all transformations are applied consistently",
        "# ml_pipeline = Pipeline([",
        "#     ('scaler', StandardScaler()),  # Or use fitted scaler",
        "#     ('classifier', RandomForestClassifier(",
        "#         n_estimators=100,",
        "#         max_depth=10,",
        "#         random_state=42",
        "#     ))",
        "# ])",
        "# ",
        "# # For regression tasks:",
        "# # from sklearn.ensemble import RandomForestRegressor",
        "# # ml_pipeline = Pipeline([",
        "# #     ('scaler', StandardScaler()),",
        "# #     ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))",
        "# # ])",
        "",
    ])
    
    # ============================================================
    # ✨ NEW: TRAIN/TEST SPLIT & MODEL TRAINING
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# TRAIN/TEST SPLIT & MODEL TRAINING",
        "# ============================================================",
        "# from sklearn.model_selection import train_test_split",
        "# ",
        "# # Separate features and target",
        "# X = df.drop('target_column', axis=1)  # ⚠️  Replace 'target_column' with your target",
        "# y = df['target_column']",
        "# ",
        "# # Split data (80% train, 20% test)",
        "# X_train, X_test, y_train, y_test = train_test_split(",
        "#     X, y, ",
        "#     test_size=0.2, ",
        "#     random_state=42,",
        "#     stratify=y  # For classification - ensures balanced classes",
        "# )",
        "# ",
        "# print(f'\\n📊 DATA SPLIT')",
        "# print('='*60)",
        "# print(f'Training set: {X_train.shape[0]} samples')",
        "# print(f'Test set: {X_test.shape[0]} samples')",
        "# print(f'Features: {X_train.shape[1]}')",
        "# ",
        "# # Train the pipeline",
        "# print(f'\\n🚀 TRAINING MODEL')",
        "# print('='*60)",
        "# ml_pipeline.fit(X_train, y_train)",
        "# print('✅ Training complete!')",
        "",
    ])
    
    # ============================================================
    # ✨ NEW: MODEL EVALUATION
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# MODEL EVALUATION",
        "# ============================================================",
        "# from sklearn.metrics import (",
        "#     accuracy_score, precision_score, recall_score, f1_score,",
        "#     classification_report, confusion_matrix, roc_auc_score",
        "# )",
        "# ",
        "# # Make predictions",
        "# y_pred = ml_pipeline.predict(X_test)",
        "# y_proba = ml_pipeline.predict_proba(X_test)  # For classification",
        "# ",
        "# # Calculate metrics",
        "# print(f'\\n📊 MODEL PERFORMANCE')",
        "# print('='*60)",
        "# print(f'Accuracy: {accuracy_score(y_test, y_pred):.3f}')",
        "# print(f'Precision: {precision_score(y_test, y_pred, average=\"weighted\"):.3f}')",
        "# print(f'Recall: {recall_score(y_test, y_pred, average=\"weighted\"):.3f}')",
        "# print(f'F1-Score: {f1_score(y_test, y_pred, average=\"weighted\"):.3f}')",
        "# ",
        "# # For binary classification:",
        "# # print(f'ROC-AUC: {roc_auc_score(y_test, y_proba[:, 1]):.3f}')",
        "# ",
        "# # Detailed report",
        "# print(f'\\n📋 CLASSIFICATION REPORT')",
        "# print('='*60)",
        "# print(classification_report(y_test, y_pred))",
        "# ",
        "# # Confusion matrix",
        "# print(f'\\n🔢 CONFUSION MATRIX')",
        "# print('='*60)",
        "# print(confusion_matrix(y_test, y_pred))",
        "# ",
        "# # Save trained model",
        "# joblib.dump(ml_pipeline, 'trained_model.pkl')",
        "# print(f'\\n💾 Saved trained model to trained_model.pkl')",
        "",
    ])
    
    # ============================================================
    # ✨ NEW: FEATURE IMPORTANCE ANALYSIS
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# FEATURE IMPORTANCE ANALYSIS",
        "# ============================================================",
        "# from sklearn.ensemble import RandomForestClassifier",
        "# from sklearn.inspection import permutation_importance",
        "# import matplotlib.pyplot as plt",
        "# ",
        "# # Method 1: Tree-based feature importance (Fast)",
        "# print(f'\\n🎯 FEATURE IMPORTANCE ANALYSIS')",
        "# print('='*60)",
        "# ",
        "# # Extract the trained model from pipeline",
        "# trained_model = ml_pipeline.named_steps['classifier']",
        "# ",
        "# # Get feature importances",
        "# if hasattr(trained_model, 'feature_importances_'):",
        "#     importances_df = pd.DataFrame({",
        "#         'feature': X_train.columns,",
        "#         'importance': trained_model.feature_importances_",
        "#     }).sort_values('importance', ascending=False)",
        "#     ",
        "#     print('\\nTop 15 Most Important Features (Impurity-based):')",
        "#     print(importances_df.head(15).to_string(index=False))",
        "#     ",
        "#     # Save to CSV",
        "#     importances_df.to_csv('feature_importance_impurity.csv', index=False)",
        "#     print('\\n💾 Saved to feature_importance_impurity.csv')",
        "# ",
        "# # Method 2: Permutation importance (More reliable but slower)",
        "# print(f'\\n🔬 PERMUTATION IMPORTANCE ANALYSIS (More Reliable)')",
        "# print('='*60)",
        "# ",
        "# perm_importance = permutation_importance(",
        "#     ml_pipeline,  # Use entire pipeline",
        "#     X_test, y_test,",
        "#     n_repeats=10,",
        "#     random_state=42,",
        "#     n_jobs=-1  # Use all CPU cores",
        "# )",
        "# ",
        "# perm_df = pd.DataFrame({",
        "#     'feature': X_test.columns,",
        "#     'importance_mean': perm_importance.importances_mean,",
        "#     'importance_std': perm_importance.importances_std",
        "# }).sort_values('importance_mean', ascending=False)",
        "# ",
        "# print('\\nTop 15 Features (Permutation Importance):')",
        "# print(perm_df.head(15).to_string(index=False))",
        "# ",
        "# # Save to CSV",
        "# perm_df.to_csv('feature_importance_permutation.csv', index=False)",
        "# print('\\n💾 Saved to feature_importance_permutation.csv')",
        "# ",
        "# # Visualize top 20 features",
        "# # plt.figure(figsize=(10, 8))",
        "# # top_20 = perm_df.head(20)",
        "# # plt.barh(top_20['feature'], top_20['importance_mean'])",
        "# # plt.xlabel('Importance')",
        "# # plt.title('Top 20 Features by Permutation Importance')",
        "# # plt.tight_layout()",
        "# # plt.savefig('feature_importance_plot.png', dpi=300, bbox_inches='tight')",
        "# # print('\\n📊 Saved plot to feature_importance_plot.png')",
        "",
    ])
    
    # ============================================================
    # ✨ NEW: HYPERPARAMETER TUNING
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# HYPERPARAMETER TUNING (OPTIONAL - Can be slow!)",
        "# ============================================================",
        "# from sklearn.model_selection import GridSearchCV, RandomizedSearchCV",
        "# from scipy.stats import randint, uniform",
        "# ",
        "# # Option 1: Grid Search (Exhaustive but slow)",
        "# param_grid = {",
        "#     'classifier__n_estimators': [50, 100, 200],",
        "#     'classifier__max_depth': [10, 20, 30, None],",
        "#     'classifier__min_samples_split': [2, 5, 10],",
        "#     'classifier__min_samples_leaf': [1, 2, 4]",
        "# }",
        "# ",
        "# grid_search = GridSearchCV(",
        "#     ml_pipeline,",
        "#     param_grid,",
        "#     cv=5,  # 5-fold cross-validation",
        "#     scoring='accuracy',",
        "#     n_jobs=-1,",
        "#     verbose=2",
        "# )",
        "# ",
        "# print(f'\\n🔍 HYPERPARAMETER TUNING (Grid Search)')",
        "# print('='*60)",
        "# print('This may take several minutes...')",
        "# grid_search.fit(X_train, y_train)",
        "# ",
        "# print(f'\\n✅ BEST PARAMETERS FOUND:')",
        "# print(grid_search.best_params_)",
        "# print(f'\\n✅ BEST CV SCORE: {grid_search.best_score_:.3f}')",
        "# ",
        "# # Test best model",
        "# best_pipeline = grid_search.best_estimator_",
        "# y_pred_tuned = best_pipeline.predict(X_test)",
        "# print(f'✅ TEST ACCURACY: {accuracy_score(y_test, y_pred_tuned):.3f}')",
        "# ",
        "# # Save best model",
        "# joblib.dump(best_pipeline, 'best_model_tuned.pkl')",
        "# print(f'\\n💾 Saved tuned model to best_model_tuned.pkl')",
        "# ",
        "# # Option 2: Randomized Search (Faster, good results)",
        "# # param_distributions = {",
        "# #     'classifier__n_estimators': randint(50, 300),",
        "# #     'classifier__max_depth': [10, 20, 30, None],",
        "# #     'classifier__min_samples_split': randint(2, 20),",
        "# #     'classifier__min_samples_leaf': randint(1, 10)",
        "# # }",
        "# # ",
        "# # random_search = RandomizedSearchCV(",
        "# #     ml_pipeline,",
        "# #     param_distributions,",
        "# #     n_iter=50,  # Number of parameter combinations to try",
        "# #     cv=5,",
        "# #     scoring='accuracy',",
        "# #     n_jobs=-1,",
        "# #     random_state=42",
        "# # )",
        "# # random_search.fit(X_train, y_train)",
        "",
    ])
    
    # ============================================================
    # ✨ NEW: CROSS-VALIDATION
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# CROSS-VALIDATION FOR ROBUST EVALUATION",
        "# ============================================================",
        "# from sklearn.model_selection import cross_val_score, StratifiedKFold",
        "# ",
        "# # 5-fold stratified cross-validation",
        "# print(f'\\n📊 5-FOLD CROSS-VALIDATION')",
        "# print('='*60)",
        "# ",
        "# cv_scores = cross_val_score(",
        "#     ml_pipeline,",
        "#     X, y,  # Use entire dataset",
        "#     cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),",
        "#     scoring='accuracy',",
        "#     n_jobs=-1",
        "# )",
        "# ",
        "# print(f'Fold scores: {cv_scores}')",
        "# print(f'Mean accuracy: {cv_scores.mean():.3f}')",
        "# print(f'Std deviation: {cv_scores.std():.3f}')",
        "# print(f'95% CI: {cv_scores.mean():.3f} ± {cv_scores.std() * 1.96:.3f}')",
        "# ",
        "# # Multiple metrics",
        "# # from sklearn.model_selection import cross_validate",
        "# # ",
        "# # scoring = ['accuracy', 'precision_weighted', 'recall_weighted', 'f1_weighted']",
        "# # cv_results = cross_validate(ml_pipeline, X, y, cv=5, scoring=scoring, n_jobs=-1)",
        "# # ",
        "# # for metric in scoring:",
        "# #     scores = cv_results[f'test_{metric}']",
        "# #     print(f'{metric}: {scores.mean():.3f} ± {scores.std():.3f}')",
        "",
    ])
    
    # ============================================================
    # PRODUCTION DEPLOYMENT GUIDE
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# PRODUCTION DEPLOYMENT GUIDE",
        "# ============================================================",
        "print('\\n📖 PRODUCTION DEPLOYMENT GUIDE:')",
        "print('='*60)",
        "print('1. Load fitted transformers:')",
        "print('   fitted = joblib.load(\"complete_pipeline.pkl\")')",
        "print('   model = joblib.load(\"trained_model.pkl\")')",
        "print('')",
        "print('2. Apply to new data in same order')",
        "print('3. Make predictions')",
        "print('')",
        "print('💡 TIP: All transformers are saved as .pkl files')",
        "print('💡 TIP: Use PCA next to identify most important features')",
        "print('💡 TIP: Check feature_importance_*.csv for feature selection')",
        "",
    ])
    
    # ============================================================
    # PRODUCTION USAGE EXAMPLE
    # ============================================================
    code_lines.extend([
        "# ============================================================",
        "# EXAMPLE: APPLY PIPELINE TO NEW DATA (PRODUCTION)",
        "# ============================================================",
        "# # Load saved pipeline and model",
        "# fitted_pipeline = joblib.load('complete_pipeline.pkl')",
        "# trained_model = joblib.load('trained_model.pkl')",
        "# ",
        "# # Load new data",
        "# new_data = pd.read_csv('new_data.csv')",
        "# ",
        "# # Apply same transformations (in order!)",
        "# # Step 1: Handle missing values (if needed)",
        "# # Step 2: Apply scaling",
        "# if 'scaler' in fitted_pipeline:",
        "#     new_data[scale_columns] = fitted_pipeline['scaler'].transform(new_data[scale_columns])",
        "# ",
        "# # Step 3: Apply encoding",
        "# if 'label_encoders' in fitted_pipeline:",
        "#     for col, le in fitted_pipeline['label_encoders'].items():",
        "#         # Handle unknown categories",
        "#         new_data[col] = new_data[col].apply(",
        "#             lambda x: le.transform([x])[0] if x in le.classes_ else -1",
        "#         )",
        "# ",
        "# # Make predictions",
        "# predictions = trained_model.predict(new_data)",
        "# probabilities = trained_model.predict_proba(new_data)  # For classification",
        "# ",
        "# print(f'\\n🎯 PREDICTIONS ON NEW DATA')",
        "# print('='*60)",
        "# print(f'Number of predictions: {len(predictions)}')",
        "# print(f'\\nFirst 10 predictions: {predictions[:10]}')",
        "# print(f'\\nPrediction distribution:')",
        "# print(pd.Series(predictions).value_counts())",
        "# ",
        "# # Save predictions",
        "# results = new_data.copy()",
        "# results['prediction'] = predictions",
        "# results['probability'] = probabilities.max(axis=1)  # Max probability",
        "# results.to_csv('predictions.csv', index=False)",
        "# print(f'\\n💾 Saved predictions to predictions.csv')",
    ])
    
    return "\n".join(code_lines)


def show_pipeline_summary():
    """
    Display a visual summary of the complete pipeline.
    Shows what operations were applied in each stage.
    """
    
    st.markdown("### 🔄 Complete Pipeline Summary")
    
    # Count operations in each stage
    cleaning_ops = 0
    skewness_ops = 0
    engineering_ops = 0
    
    if 'cleaning_ops' in st.session_state and st.session_state.cleaning_ops:
        ops = st.session_state.cleaning_ops
        cleaning_ops = (
            len(ops.get('impute_mean', [])) +
            len(ops.get('impute_mode', [])) +
            len(ops.get('drop_cols', [])) +
            (1 if ops.get('drop_duplicates') else 0) +
            (1 if ops.get('outlier_treatment') else 0)
        )
    
    if 'transformations_log' in st.session_state:
        skewness_ops = len(st.session_state.transformations_log)
    
    if 'engineering_operations' in st.session_state:
        eng_ops = st.session_state.engineering_operations
        engineering_ops = (
            (1 if eng_ops.get('scaling') else 0) +
            (1 if eng_ops.get('encoding') else 0) +
            len(eng_ops.get('additional', []))
        )
    
    # Display metrics
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric("🛠️ Cleaning", cleaning_ops, 
                 help="Operations from Fix Data tab")
    
    with col2:
        st.metric("📐 Skewness", skewness_ops,
                 help="Transformations from Skewness tab")
    
    with col3:
        st.metric("🔧 Engineering", engineering_ops,
                 help="Operations from Feature Engineering tab")
    
    with col4:
        total = cleaning_ops + skewness_ops + engineering_ops
        st.metric("📊 Total Ops", total,
                 help="Total pipeline operations")
    
    # Show detailed breakdown
    if total > 0:
        with st.expander("📋 Detailed Operation Breakdown", expanded=False):
            
            # Cleaning operations
            if cleaning_ops > 0:
                st.markdown("**🛠️ Data Cleaning:**")
                if 'cleaning_ops' in st.session_state:
                    ops = st.session_state.cleaning_ops
                    if ops.get('impute_mean'):
                        st.write(f"  • Mean imputation: {len(ops['impute_mean'])} columns")
                    if ops.get('impute_mode'):
                        st.write(f"  • Mode imputation: {len(ops['impute_mode'])} columns")
                    if ops.get('drop_cols'):
                        st.write(f"  • Dropped columns: {len(ops['drop_cols'])}")
                    if ops.get('drop_duplicates'):
                        st.write(f"  • Removed duplicates: Yes")
                    if ops.get('outlier_treatment'):
                        st.write(f"  • Outlier treatment: {ops['outlier_treatment'].upper()}")
                st.write("")
            
            # Skewness corrections
            if skewness_ops > 0:
                st.markdown("**📐 Skewness Corrections:**")
                transforms = st.session_state.transformations_log
                for t in transforms:
                    improvement = ((abs(t['original_skew']) - abs(t['new_skew'])) / 
                                 abs(t['original_skew']) * 100) if t['original_skew'] != 0 else 0
                    st.write(f"  • {t['column']}: {t['method']} ({improvement:.1f}% improvement)")
                st.write("")
            
            # Feature engineering
            if engineering_ops > 0:
                st.markdown("**🔧 Feature Engineering:**")
                eng_ops = st.session_state.engineering_operations
                if eng_ops.get('scaling'):
                    scaling_method = eng_ops['scaling']['method'].split('(')[0].strip()
                    st.write(f"  • Scaling: {scaling_method} on {len(eng_ops['scaling']['columns'])} cols")
                if eng_ops.get('encoding'):
                    encoding_method = eng_ops['encoding']['method'].split('(')[0].strip()
                    st.write(f"  • Encoding: {encoding_method} on {len(eng_ops['encoding']['columns'])} cols")
                for transform in eng_ops.get('additional', []):
                    trans_type = transform['type'].title()
                    col_count = len(transform.get('columns', []))
                    st.write(f"  • {trans_type} transform on {col_count} cols")
    
    else:
        st.info("💡 No pipeline operations recorded yet. Apply transformations in Fix Data, Skewness, or Feature Engineering tabs!")
        
    # Show next recommendation
    if total > 0:
        st.markdown("---")
        
        # Check if PCA would be useful
        if 'engineered_df' in st.session_state and st.session_state.engineered_df is not None:
            n_features = len(st.session_state.engineered_df.columns)
            if n_features > 20:
                st.info(
                    f"💡 **Recommendation:** You have {n_features} features. "
                    f"Visit the **PCA tab** to reduce dimensionality and identify most important features!",
                    icon="📊"
                )
            else:
                st.success(
                    "✅ **Ready for modeling!** Your data is fully prepared. "
                    "Download the complete pipeline code and start training!",
                    icon="🚀"
                )